version: 2.1

executor_defaults: &executor_defaults
  working_directory: ~/repo

# We exercise the following JVMs:
# * those officially supported by Clojure (atm: 8 and 11)
# * plus, whatever the latest version is.
executors:
  openjdk8:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.5
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    <<: *executor_defaults
  openjdk11:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.5
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m --illegal-access=deny
    <<: *executor_defaults
  openjdk16:
    docker:
      - image: circleci/clojure:openjdk-16-lein-2.9.5-buster
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m --illegal-access=deny
    <<: *executor_defaults

jobs:
  test:
    parameters:
      executor:
        type: executor
      clojure-version:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Fetch dependencies
          command: |
            lein with-profile +test deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Run test suite
          command: lein with-profile -user,-dev,+test,+<< parameters.clojure-version >> do clean, test

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              executor: [openjdk8, openjdk11, openjdk16]
              clojure-version: ["1.7", "1.8", "1.9", "1.10"]
