version: 2
jobs:
  build:
    working_directory: ~/clj-http-lite
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: clj-http-lite-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: clj-http-lote-{{ checksum "project.clj" }}
      - run: lein all do clean, test :all
